apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"forms-flow-documents"},"name":"forms-flow-documents","namespace":"d89793-prod"},"spec":{"replicas":1,"selector":{"app":"forms-flow-documents"},"strategy":{"activeDeadlineSeconds":21600,"resources":{},"rollingParams":{"intervalSeconds":1,"maxSurge":"25%","maxUnavailable":"25%","timeoutSeconds":700,"updatePeriodSeconds":1},"type":"Rolling"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"forms-flow-documents"}},"spec":{"containers":[{"env":[{"name":"KEYCLOAK_URL","valueFrom":{"secretKeyRef":{"key":"keycloak_url","name":"forms-flow-ai-secret"}}},{"name":"KEYCLOAK_URL_REALM","valueFrom":{"secretKeyRef":{"key":"keycloak_realm","name":"forms-flow-ai-secret"}}},{"name":"DATABASE_URL","valueFrom":{"secretKeyRef":{"key":"DATABASE_URL","name":"forms-flow-ai-config"}}},{"name":"JWT_OIDC_AUDIENCE","valueFrom":{"secretKeyRef":{"key":"JWT_OIDC_AUDIENCE","name":"forms-flow-ai-config"}}},{"name":"JWT_OIDC_CACHING_ENABLED","valueFrom":{"secretKeyRef":{"key":"JWT_OIDC_CACHING_ENABLED","name":"forms-flow-ai-config"}}},{"name":"JWT_OIDC_ISSUER","valueFrom":{"secretKeyRef":{"key":"JWT_OIDC_ISSUER","name":"forms-flow-ai-config"}}},{"name":"JWT_OIDC_JWKS_URI","valueFrom":{"secretKeyRef":{"key":"JWT_OIDC_JWKS_URI","name":"forms-flow-ai-config"}}},{"name":"JWT_OIDC_WELL_KNOWN_CONFIG","valueFrom":{"secretKeyRef":{"key":"JWT_OIDC_WELL_KNOWN_CONFIG","name":"forms-flow-ai-config"}}},{"name":"FORMSFLOW_API_CORS_ORIGINS","value":"*"},{"name":"FORMIO_URL","valueFrom":{"secretKeyRef":{"key":"FORMIO_URL","name":"forms-flow-ai-config"}}},{"name":"FORMIO_ROOT_EMAIL","valueFrom":{"secretKeyRef":{"key":"FORMIO_ROOT_EMAIL","name":"forms-flow-ai-config"}}},{"name":"FORMIO_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"FORMIO_ROOT_PASSWORD","name":"forms-flow-ai-config"}}},{"name":"KEYCLOAK_ENABLE_CLIENT_AUTH","valueFrom":{"configMapKeyRef":{"key":"KEYCLOAK_ENABLE_CLIENT_AUTH","name":"forms-flow-ai-config"}}},{"name":"FORMSFLOW_API_URL","valueFrom":{"configMapKeyRef":{"key":"WEB_API_BASE_URL","name":"forms-flow-ai-config"}}},{"name":"FORMSFLOW_DOC_API_URL","valueFrom":{"configMapKeyRef":{"key":"FORMSFLOW_DOC_API_URL","name":"forms-flow-ai-config"}}},{"name":"CHROME_DRIVER_PATH","valueFrom":{"configMapKeyRef":{"key":"CHROME_DRIVER_PATH","name":"forms-flow-ai-config"}}},{"name":"FORMIO_JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"FORMIO_JWT_SECRET","name":"forms-flow-ai-config"}}}],"image":"image-registry.openshift-image-registry.svc:5000/d89793-tools/forms-flow-documents:production","name":"forms-flow-documents","ports":[{"containerPort":5006}],"resources":{},"stdin":true,"tty":true}],"restartPolicy":"Always"}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["forms-flow-documents"],"from":{"kind":"ImageStreamTag","name":"forms-flow-documents:production","namespace":"d89793-tools"}},"type":"ImageChange"}]},"status":{}}
  creationTimestamp: "2023-01-18T01:23:08Z"
  generation: 65
  labels:
    app: forms-flow-documents
  name: forms-flow-documents
  namespace: d89793-prod
  resourceVersion: "13900045627"
  uid: 4cc022d7-ce09-46f0-a85d-75253f29178a
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: forms-flow-documents
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 700
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: forms-flow-documents
    spec:
      containers:
      - env:
        - name: KEYCLOAK_URL
          valueFrom:
            secretKeyRef:
              key: keycloak_url
              name: forms-flow-ai-secret
        - name: KEYCLOAK_URL_REALM
          valueFrom:
            secretKeyRef:
              key: keycloak_realm
              name: forms-flow-ai-secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: forms-flow-ai-config
        - name: JWT_OIDC_AUDIENCE
          valueFrom:
            secretKeyRef:
              key: JWT_OIDC_AUDIENCE
              name: forms-flow-ai-config
        - name: JWT_OIDC_CACHING_ENABLED
          valueFrom:
            secretKeyRef:
              key: JWT_OIDC_CACHING_ENABLED
              name: forms-flow-ai-config
        - name: JWT_OIDC_ISSUER
          valueFrom:
            secretKeyRef:
              key: JWT_OIDC_ISSUER
              name: forms-flow-ai-config
        - name: JWT_OIDC_JWKS_URI
          valueFrom:
            secretKeyRef:
              key: JWT_OIDC_JWKS_URI
              name: forms-flow-ai-config
        - name: JWT_OIDC_WELL_KNOWN_CONFIG
          valueFrom:
            secretKeyRef:
              key: JWT_OIDC_WELL_KNOWN_CONFIG
              name: forms-flow-ai-config
        - name: FORMSFLOW_API_CORS_ORIGINS
          value: '*'
        - name: FORMIO_URL
          valueFrom:
            secretKeyRef:
              key: FORMIO_URL
              name: forms-flow-ai-config
        - name: FORMIO_ROOT_EMAIL
          valueFrom:
            secretKeyRef:
              key: FORMIO_ROOT_EMAIL
              name: forms-flow-ai-config
        - name: FORMIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: FORMIO_ROOT_PASSWORD
              name: forms-flow-ai-config
        - name: KEYCLOAK_ENABLE_CLIENT_AUTH
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ENABLE_CLIENT_AUTH
              name: forms-flow-ai-config
        - name: FORMSFLOW_API_URL
          valueFrom:
            configMapKeyRef:
              key: WEB_API_BASE_URL
              name: forms-flow-ai-config
        - name: FORMSFLOW_DOC_API_URL
          valueFrom:
            configMapKeyRef:
              key: FORMSFLOW_DOC_API_URL
              name: forms-flow-ai-config
        - name: CHROME_DRIVER_PATH
          valueFrom:
            configMapKeyRef:
              key: CHROME_DRIVER_PATH
              name: forms-flow-ai-config
        - name: FORMIO_JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: FORMIO_JWT_SECRET
              name: forms-flow-ai-config
        image: image-registry.openshift-image-registry.svc:5000/d89793-tools/forms-flow-documents@sha256:ea0ed6ec66e1f97b5bb457611b870aa7a4703f49c0ccd2ea86752976fd650a91
        imagePullPolicy: IfNotPresent
        name: forms-flow-documents
        ports:
        - containerPort: 5006
          protocol: TCP
        resources:
          limits:
            cpu: 1400m
            memory: 3Gi
          requests:
            cpu: 600m
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - forms-flow-documents
      from:
        kind: ImageStreamTag
        name: forms-flow-documents:production
        namespace: d89793-tools
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/d89793-tools/forms-flow-documents@sha256:ea0ed6ec66e1f97b5bb457611b870aa7a4703f49c0ccd2ea86752976fd650a91
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-09T00:52:20Z"
    lastUpdateTime: "2024-04-09T00:52:26Z"
    message: replication controller "forms-flow-documents-42" successfully rolled
      out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-02T12:57:46Z"
    lastUpdateTime: "2025-04-02T12:57:46Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 42
  observedGeneration: 65
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
