apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"forms-flow-analytics-scheduler"},"name":"forms-flow-analytics-scheduler","namespace":"d89793-prod"},"spec":{"replicas":1,"selector":{"app":"forms-flow-analytics-scheduler"},"strategy":{"resources":{}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"forms-flow-analytics-scheduler"}},"spec":{"containers":[{"args":["scheduler"],"env":[{"name":"POSTGRES_HOST_AUTH_METHOD","valueFrom":{"secretKeyRef":{"key":"POSTGRES_HOST_AUTH_METHOD","name":"forms-flow-analytics"}}},{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"forms-flow-analytics"}}},{"name":"PYTHONUNBUFFERED","valueFrom":{"secretKeyRef":{"key":"PYTHONUNBUFFERED","name":"forms-flow-analytics"}}},{"name":"REDASH_COOKIE_SECRET","valueFrom":{"secretKeyRef":{"key":"REDASH_COOKIE_SECRET","name":"forms-flow-analytics"}}},{"name":"REDASH_DATABASE_URL","valueFrom":{"secretKeyRef":{"key":"REDASH_DATABASE_URL","name":"forms-flow-analytics"}}},{"name":"REDASH_HOST","valueFrom":{"secretKeyRef":{"key":"REDASH_HOST","name":"forms-flow-analytics"}}},{"name":"REDASH_LOG_LEVEL","valueFrom":{"secretKeyRef":{"key":"REDASH_LOG_LEVEL","name":"forms-flow-analytics"}}},{"name":"REDASH_REDIS_URL","valueFrom":{"secretKeyRef":{"key":"REDASH_REDIS_URL","name":"forms-flow-analytics"}}},{"name":"REDASH_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"REDASH_SECRET_KEY","name":"forms-flow-analytics"}}},{"name":"REDASH_REFERRER_POLICY","valueFrom":{"secretKeyRef":{"key":"REDASH_REFERRER_POLICY","name":"forms-flow-analytics"}}},{"name":"REDASH_CORS_ACCESS_CONTROL_ALLOW_HEADERS","valueFrom":{"secretKeyRef":{"key":"REDASH_CORS_ACCESS_CONTROL_ALLOW_HEADERS","name":"forms-flow-analytics"}}},{"name":"REDASH_CORS_ACCESS_CONTROL_ALLOW_ORIGIN","valueFrom":{"secretKeyRef":{"key":"REDASH_CORS_ACCESS_CONTROL_ALLOW_ORIGIN","name":"forms-flow-analytics"}}}],"image":"image-registry.openshift-image-registry.svc:5000/d89793-prod/forms-flow-analytics:latest","name":"forms-flow-analytics-scheduler","resources":{}}],"restartPolicy":"Always"}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["forms-flow-analytics-scheduler"],"from":{"kind":"ImageStreamTag","name":"forms-flow-analytics:latest","namespace":"d89793-prod"}},"type":"ImageChange"}]},"status":{}}
  creationTimestamp: "2022-03-18T14:15:59Z"
  generation: 12
  labels:
    app: forms-flow-analytics-scheduler
  name: forms-flow-analytics-scheduler
  namespace: d89793-prod
  resourceVersion: "8092669944"
  uid: 706c235b-0e35-4ab0-8b7b-fcfa89843614
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    app: forms-flow-analytics-scheduler
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: forms-flow-analytics-scheduler
    spec:
      containers:
      - args:
        - scheduler
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_HOST_AUTH_METHOD
              name: forms-flow-analytics
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: forms-flow-analytics
        - name: PYTHONUNBUFFERED
          valueFrom:
            secretKeyRef:
              key: PYTHONUNBUFFERED
              name: forms-flow-analytics
        - name: REDASH_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: REDASH_COOKIE_SECRET
              name: forms-flow-analytics
        - name: REDASH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: REDASH_DATABASE_URL
              name: forms-flow-analytics
        - name: REDASH_HOST
          valueFrom:
            secretKeyRef:
              key: REDASH_HOST
              name: forms-flow-analytics
        - name: REDASH_LOG_LEVEL
          valueFrom:
            secretKeyRef:
              key: REDASH_LOG_LEVEL
              name: forms-flow-analytics
        - name: REDASH_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: REDASH_REDIS_URL
              name: forms-flow-analytics
        - name: REDASH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: REDASH_SECRET_KEY
              name: forms-flow-analytics
        - name: REDASH_REFERRER_POLICY
          valueFrom:
            secretKeyRef:
              key: REDASH_REFERRER_POLICY
              name: forms-flow-analytics
        - name: REDASH_CORS_ACCESS_CONTROL_ALLOW_HEADERS
          valueFrom:
            secretKeyRef:
              key: REDASH_CORS_ACCESS_CONTROL_ALLOW_HEADERS
              name: forms-flow-analytics
        - name: REDASH_CORS_ACCESS_CONTROL_ALLOW_ORIGIN
          valueFrom:
            secretKeyRef:
              key: REDASH_CORS_ACCESS_CONTROL_ALLOW_ORIGIN
              name: forms-flow-analytics
        image: image-registry.openshift-image-registry.svc:5000/d89793-prod/forms-flow-analytics@sha256:582ae6d1c3eeb9c485cacb0fedde04a10af1cb8700abd826635cb7021937760e
        imagePullPolicy: Always
        name: forms-flow-analytics-scheduler
        resources:
          limits:
            cpu: 20m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - forms-flow-analytics-scheduler
      from:
        kind: ImageStreamTag
        name: forms-flow-analytics:production
        namespace: d89793-prod
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/d89793-prod/forms-flow-analytics@sha256:582ae6d1c3eeb9c485cacb0fedde04a10af1cb8700abd826635cb7021937760e
    type: ImageChange
status:
  availableReplicas: 0
  conditions:
  - lastTransitionTime: "2023-02-16T02:04:17Z"
    lastUpdateTime: "2023-02-16T02:04:21Z"
    message: replication controller "forms-flow-analytics-scheduler-7" successfully
      rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-10-31T15:44:40Z"
    lastUpdateTime: "2023-10-31T15:44:40Z"
    message: Deployment config does not have minimum availability.
    status: "False"
    type: Available
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: image-registry.openshift-image-registry.svc:5000/d89793-prod/forms-flow-analytics@sha256:582ae6d1c3eeb9c485cacb0fedde04a10af1cb8700abd826635cb7021937760e
      type: ImageChange
    message: image change
  latestVersion: 7
  observedGeneration: 12
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
