apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"labels":{"app":"forms-flow-bpm"},"name":"forms-flow-bpm","namespace":"d89793-dev"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"app":"forms-flow-bpm"},"strategy":{"activeDeadlineSeconds":21600,"resources":{},"rollingParams":{"intervalSeconds":1,"maxSurge":"25%","maxUnavailable":"25%","timeoutSeconds":600,"updatePeriodSeconds":1},"type":"Rolling"},"template":{"metadata":{"labels":{"app":"forms-flow-bpm"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"name","operator":"In","values":["forms-flow-bpm"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"env":[{"name":"APP_SECURITY_ORIGIN","value":"*"},{"name":"CAMUNDA_JDBC_URL","value":"jdbc:postgresql://patroni:5432/formsflow-bpm"},{"name":"WAIT_FOR","value":"patroni:5432"},{"name":"KEYCLOAK_URL","valueFrom":{"configMapKeyRef":{"key":"KEYCLOAK_URL","name":"forms-flow-ai-config"}}},{"name":"KEYCLOAK_URL_REALM","valueFrom":{"secretKeyRef":{"key":"keycloak_realm","name":"forms-flow-ai-secret"}}},{"name":"KEYCLOAK_CLIENTID","valueFrom":{"secretKeyRef":{"key":"keycloak_clientid","name":"forms-flow-ai-secret"}}},{"name":"KEYCLOAK_CLIENTSECRET","valueFrom":{"secretKeyRef":{"key":"keycloak_clientsecret","name":"forms-flow-ai-secret"}}},{"name":"DEBUG","value":"False"},{"name":"MAIL_CONFIG","value":"/app/mail-config.properties"},{"name":"TZ","value":"UTC"},{"name":"CAMUNDA_MAX_POOLSIZE","value":"20"},{"name":"CAMUNDA_CONN_TIMEOUT","value":"90000"},{"name":"CAMUNDA_HIKARI_MAX_POOLSIZE","value":"10"},{"name":"CAMUNDA_ANALYTICS_JDBC_URL","valueFrom":{"configMapKeyRef":{"key":"CAMUNDA_ANALYTICS_JDBC_URL","name":"forms-flow-ai-config"}}},{"name":"CAMUNDA_FORMBUILDER_PIPELINE_USERNAME","valueFrom":{"secretKeyRef":{"key":"camunda_formbuilder_pipeline_username","name":"forms-flow-ai-secret"}}},{"name":"CAMUNDA_JOB_CORE_POOL_SIZE","value":"3"},{"name":"CAMUNDA_JOB_LOCK_TIME_MILLIS","value":"90000"},{"name":"CAMUNDA_ANALYTICS_HIKARI_VALID_TIMEOUT","value":"90000"},{"name":"CAMUNDA_JDBC_DRIVER","value":"org.postgresql.Driver"},{"name":"FORMIO_ROOT_EMAIL","valueFrom":{"secretKeyRef":{"key":"formio_root_email","name":"forms-flow-ai-secret"}}},{"name":"CAMUNDA_ANALYTICS_HIKARI_IDLE_TIMEOUT","value":"90000"},{"name":"FORMIO_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"formio_root_password","name":"forms-flow-ai-secret"}}},{"name":"CAMUNDA_JDBC_USER","valueFrom":{"configMapKeyRef":{"key":"CAMUNDA_JDBC_USER","name":"forms-flow-ai-config"}}},{"name":"CAMUNDA_ANALYTICS_HIKARI_MAX_POOLSIZE","value":"10"},{"name":"CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"camunda_formbuilder_pipeline_password","name":"forms-flow-ai-secret"}}},{"name":"CAMUNDA_ANALYTICS_JDBC_DRIVER","value":"com.microsoft.sqlserver.jdbc.SQLServerDriver"},{"name":"CAMUNDA_HIKARI_VALID_TIMEOUT","value":"90000"},{"name":"CAMUNDA_ANALYTICS_JDBC_USER","valueFrom":{"secretKeyRef":{"key":"camunda_analytics_jdbc_user","name":"forms-flow-ai-secret"}}},{"name":"CAMUNDA_JOB_WAIT_TIME_MILLIS","value":"90000"},{"name":"CAMUNDA_JOB_QUEUE_SIZE","value":"3"},{"name":"CAMUNDA_JOB_MAX_WAIT","value":"60000"},{"name":"CAMUNDA_BPM_HISTORY_LEVEL","value":"NONE"},{"name":"CAMUNDA_JDBC_PASSWORD","valueFrom":{"secretKeyRef":{"key":"db_password","name":"forms-flow-ai-secret"}}},{"name":"CAMUNDA_HIKARI_CONN_TIMEOUT","value":"60000"},{"name":"CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL","valueFrom":{"configMapKeyRef":{"key":"CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL","name":"forms-flow-ai-config"}}},{"name":"CAMUNDA_JDBC_DB","value":"formsflow-bpm"},{"name":"FORMSFLOW_API_URL","valueFrom":{"configMapKeyRef":{"key":"WEB_API_BASE_URL","name":"forms-flow-ai-config"}}},{"name":"CAMUNDA_JOB_MAXJOBS_PER_ACQUISITION","value":"3"},{"name":"FORMIO_URL","valueFrom":{"configMapKeyRef":{"key":"FORMIO_URL","name":"forms-flow-ai-config"}}},{"name":"FORMIO_FILE_URL","valueFrom":{"configMapKeyRef":{"key":"CAMUNDA_FORMIO_FILE_URL","name":"forms-flow-ai-config"}}},{"name":"CAMUNDA_ANALYTICS_JDBC_PASSWORD","valueFrom":{"secretKeyRef":{"key":"camunda_analytics_jdbc_password","name":"forms-flow-ai-secret"}}},{"name":"CAMUNDA_APP_ROOT_LOG_FLAG","value":"info"},{"name":"CAMUNDA_ANALYTICS_HIKARI_CONN_TIMEOUT","value":"90000"},{"name":"CAMUNDA_HIKARI_IDLE_TIMEOUT","value":"90000"},{"name":"CAMUNDA_JOB_MAX_POOL_SIZE","value":"10"},{"name":"WEBSOCKET_ENCRYPT_KEY","value":"8vmDx5EtU6gsCenxfg43eY74vVXaNxmPYaSMqabvJzQQkPT"},{"name":"WEBSOCKET_MESSAGE_TYPE","value":"TASK_EVENT"},{"name":"WEBSOCKET_SECURITY_ORIGIN","value":"https://digital-journeys-camunda-dev.apps.silver.devops.gov.bc.ca,digital-journeys-forms-flow-dev.apps.silver.devops.gov.bc.ca"},{"name":"DATA_BUFFER_SIZE","value":"32"},{"name":"IDENTITY_PROVIDER_MAX_RESULT_SIZE","value":"250"},{"name":"WEB_BASE_URL","valueFrom":{"secretKeyRef":{"key":"WEB_BASE_URL","name":"forms-flow-ai-secret"}}},{"name":"ODS_URL","valueFrom":{"secretKeyRef":{"key":"ODS_URL","name":"forms-flow-ai-config"}}},{"name":"ODS_AUTH_TOKEN","valueFrom":{"secretKeyRef":{"key":"ODS_AUTH_TOKEN","name":"forms-flow-ai-config"}}},{"name":"FORMSFLOW_DOC_API_URL","valueFrom":{"configMapKeyRef":{"key":"FORMSFLOW_DOC_API_URL","name":"forms-flow-ai-config"}}},{"name":"BPM_CLIENT_CONN_TIMEOUT","valueFrom":{"configMapKeyRef":{"key":"BPM_CLIENT_CONN_TIMEOUT","name":"forms-flow-ai-config"}}},{"name":"CRM_URL","valueFrom":{"secretKeyRef":{"key":"CRM_URL","name":"forms-flow-ai-config"}}},{"name":"CRM_AUTH_TOKEN","valueFrom":{"secretKeyRef":{"key":"CRM_AUTH_TOKEN","name":"forms-flow-ai-config"}}}],"image":"image-registry.openshift-image-registry.svc:5000/d89793-tools/forms-flow-bpm:dev","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":4,"httpGet":{"path":"/camunda/actuator/health","port":8080,"scheme":"HTTP"},"initialDelaySeconds":120,"periodSeconds":20,"successThreshold":1,"timeoutSeconds":90},"name":"forms-flow-bpm","ports":[{"containerPort":8080,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":4,"httpGet":{"path":"/camunda/actuator/health","port":8080,"scheme":"HTTP"},"initialDelaySeconds":120,"periodSeconds":120,"successThreshold":1,"timeoutSeconds":4},"resources":{"limits":{"cpu":"400m","memory":"2Gi"},"requests":{"cpu":"100m","memory":"1Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/app/mail-config.properties","name":"forms-flow-bpm-mail-config","subPath":"mail-config.properties"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"items":[{"key":"mail-config.properties","path":"mail-config.properties"}],"name":"forms-flow-bpm-mail-config"},"name":"forms-flow-bpm-mail-config"}]}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["forms-flow-bpm"],"from":{"kind":"ImageStreamTag","name":"forms-flow-bpm:dev","namespace":"d89793-tools"}},"type":"ImageChange"}]}}
  creationTimestamp: "2022-01-17T22:31:55Z"
  generation: 928
  labels:
    app: forms-flow-bpm
  name: forms-flow-bpm
  namespace: d89793-dev
  resourceVersion: "13807793366"
  uid: 781d49aa-6c51-4c49-9fc7-cd07afb4e12b
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: forms-flow-bpm
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: forms-flow-bpm
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - forms-flow-bpm
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: APP_SECURITY_ORIGIN
          value: '*'
        - name: CAMUNDA_JDBC_URL
          value: jdbc:postgresql://patroni:5432/formsflow-bpm
        - name: WAIT_FOR
          value: patroni:5432
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_URL
              name: forms-flow-ai-config
        - name: KEYCLOAK_URL_REALM
          valueFrom:
            secretKeyRef:
              key: keycloak_realm
              name: forms-flow-ai-secret
        - name: KEYCLOAK_CLIENTID
          valueFrom:
            secretKeyRef:
              key: keycloak_clientid
              name: forms-flow-ai-secret
        - name: KEYCLOAK_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              key: keycloak_clientsecret
              name: forms-flow-ai-secret
        - name: DEBUG
          value: "False"
        - name: MAIL_CONFIG
          value: /app/mail-config.properties
        - name: TZ
          value: UTC
        - name: CAMUNDA_MAX_POOLSIZE
          value: "20"
        - name: CAMUNDA_CONN_TIMEOUT
          value: "90000"
        - name: CAMUNDA_HIKARI_MAX_POOLSIZE
          value: "10"
        - name: CAMUNDA_ANALYTICS_JDBC_URL
          valueFrom:
            configMapKeyRef:
              key: CAMUNDA_ANALYTICS_JDBC_URL
              name: forms-flow-ai-config
        - name: CAMUNDA_FORMBUILDER_PIPELINE_USERNAME
          valueFrom:
            secretKeyRef:
              key: camunda_formbuilder_pipeline_username
              name: forms-flow-ai-secret
        - name: CAMUNDA_JOB_CORE_POOL_SIZE
          value: "3"
        - name: CAMUNDA_JOB_LOCK_TIME_MILLIS
          value: "90000"
        - name: CAMUNDA_ANALYTICS_HIKARI_VALID_TIMEOUT
          value: "90000"
        - name: CAMUNDA_JDBC_DRIVER
          value: org.postgresql.Driver
        - name: FORMIO_ROOT_EMAIL
          valueFrom:
            secretKeyRef:
              key: formio_root_email
              name: forms-flow-ai-secret
        - name: CAMUNDA_ANALYTICS_HIKARI_IDLE_TIMEOUT
          value: "90000"
        - name: FORMIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: formio_root_password
              name: forms-flow-ai-secret
        - name: CAMUNDA_JDBC_USER
          valueFrom:
            configMapKeyRef:
              key: CAMUNDA_JDBC_USER
              name: forms-flow-ai-config
        - name: CAMUNDA_ANALYTICS_HIKARI_MAX_POOLSIZE
          value: "10"
        - name: CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: camunda_formbuilder_pipeline_password
              name: forms-flow-ai-secret
        - name: CAMUNDA_ANALYTICS_JDBC_DRIVER
          value: com.microsoft.sqlserver.jdbc.SQLServerDriver
        - name: CAMUNDA_HIKARI_VALID_TIMEOUT
          value: "90000"
        - name: CAMUNDA_ANALYTICS_JDBC_USER
          valueFrom:
            secretKeyRef:
              key: camunda_analytics_jdbc_user
              name: forms-flow-ai-secret
        - name: CAMUNDA_JOB_WAIT_TIME_MILLIS
          value: "90000"
        - name: CAMUNDA_JOB_QUEUE_SIZE
          value: "3"
        - name: CAMUNDA_JOB_MAX_WAIT
          value: "60000"
        - name: CAMUNDA_BPM_HISTORY_LEVEL
          value: NONE
        - name: CAMUNDA_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_password
              name: forms-flow-ai-secret
        - name: CAMUNDA_HIKARI_CONN_TIMEOUT
          value: "60000"
        - name: CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL
          valueFrom:
            configMapKeyRef:
              key: CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL
              name: forms-flow-ai-config
        - name: CAMUNDA_JDBC_DB
          value: formsflow-bpm
        - name: FORMSFLOW_API_URL
          valueFrom:
            configMapKeyRef:
              key: WEB_API_BASE_URL
              name: forms-flow-ai-config
        - name: CAMUNDA_JOB_MAXJOBS_PER_ACQUISITION
          value: "3"
        - name: FORMIO_URL
          valueFrom:
            configMapKeyRef:
              key: FORMIO_URL
              name: forms-flow-ai-config
        - name: FORMIO_FILE_URL
          valueFrom:
            configMapKeyRef:
              key: CAMUNDA_FORMIO_FILE_URL
              name: forms-flow-ai-config
        - name: CAMUNDA_ANALYTICS_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: camunda_analytics_jdbc_password
              name: forms-flow-ai-secret
        - name: CAMUNDA_APP_ROOT_LOG_FLAG
          value: info
        - name: CAMUNDA_ANALYTICS_HIKARI_CONN_TIMEOUT
          value: "90000"
        - name: CAMUNDA_HIKARI_IDLE_TIMEOUT
          value: "90000"
        - name: CAMUNDA_JOB_MAX_POOL_SIZE
          value: "10"
        - name: WEBSOCKET_ENCRYPT_KEY
          value: 8vmDx5EtU6gsCenxfg43eY74vVXaNxmPYaSMqabvJzQQkPT
        - name: WEBSOCKET_MESSAGE_TYPE
          value: TASK_EVENT
        - name: WEBSOCKET_SECURITY_ORIGIN
          value: https://digital-journeys-camunda-dev.apps.silver.devops.gov.bc.ca,digital-journeys-forms-flow-dev.apps.silver.devops.gov.bc.ca
        - name: DATA_BUFFER_SIZE
          value: "32"
        - name: IDENTITY_PROVIDER_MAX_RESULT_SIZE
          value: "250"
        - name: WEB_BASE_URL
          valueFrom:
            secretKeyRef:
              key: WEB_BASE_URL
              name: forms-flow-ai-secret
        - name: ODS_URL
          valueFrom:
            secretKeyRef:
              key: ODS_URL
              name: forms-flow-ai-config
        - name: ODS_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: ODS_AUTH_TOKEN
              name: forms-flow-ai-config
        - name: FORMSFLOW_DOC_API_URL
          valueFrom:
            configMapKeyRef:
              key: FORMSFLOW_DOC_API_URL
              name: forms-flow-ai-config
        - name: BPM_CLIENT_CONN_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: BPM_CLIENT_CONN_TIMEOUT
              name: forms-flow-ai-config
        - name: CRM_URL
          valueFrom:
            secretKeyRef:
              key: CRM_URL
              name: forms-flow-ai-config
        - name: CRM_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: CRM_AUTH_TOKEN
              name: forms-flow-ai-config
        image: image-registry.openshift-image-registry.svc:5000/d89793-tools/forms-flow-bpm@sha256:2a3438267c6049492ecf1961edcc8c0ca54a3e50e7f9468e8e1a16e7723e8587
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /camunda/actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 90
        name: forms-flow-bpm
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /camunda/actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 4
        resources:
          limits:
            cpu: 400m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/mail-config.properties
          name: forms-flow-bpm-mail-config
          subPath: mail-config.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: mail-config.properties
            path: mail-config.properties
          name: forms-flow-bpm-mail-config
        name: forms-flow-bpm-mail-config
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - forms-flow-bpm
      from:
        kind: ImageStreamTag
        name: forms-flow-bpm:dev
        namespace: d89793-tools
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/d89793-tools/forms-flow-bpm@sha256:2a3438267c6049492ecf1961edcc8c0ca54a3e50e7f9468e8e1a16e7723e8587
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-09-23T20:51:27Z"
    lastUpdateTime: "2024-09-23T20:51:31Z"
    message: replication controller "forms-flow-bpm-586" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-03-26T19:20:47Z"
    lastUpdateTime: "2025-03-26T19:20:47Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: image-registry.openshift-image-registry.svc:5000/d89793-tools/forms-flow-bpm@sha256:2a3438267c6049492ecf1961edcc8c0ca54a3e50e7f9468e8e1a16e7723e8587
      type: ImageChange
    message: image change
  latestVersion: 586
  observedGeneration: 928
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
